#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: exoscale
pathToKey: /home/ipelu/.ssh/id_rsa
authFile: /home/ipelu/Desktop/work/clouds/exoscale/creds
flavor: Small # Medium
zone: ch-gva-2 # at-vie-1 # de-fra-1
template: "Linux CentOS 7 64-bit"
keyPair: k_cl
securityGroups: ["default"]
storageCapacity: 100

#---------------COST CALCULATION------------------------------------------------
#costCalculation:
#  generalInstancePrice: 0.2
#  GPUInstancePrice: 0.2
#  HPCInstancePrice: 0.2
#  s3bucketPrice: 0.1
