#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: "google"
pathToKey: "/root/.ssh/id_rsa"
dockerCE:
dockerEngine:
kubernetes:
openUser: openu
flavor: "n1-standard-2"
zone: "us-west1-a"
image: "centos-cloud/centos-7"
pathToCredentials: "/gcp.json"
project: "ocrets"
gpuType: "nvidia-tesla-p100" # this is only required when the GAN test is selected. Schema has to check this

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
