#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
general:
  slaves_amount:
  provider_name:
  provider_instance_name:
  path_to_key:

credentials:
  key:
  secret: 

instance_definition:

#---------------TEST CATALOG----------------------------------------------------
tests_catalog:
  s3_test:
    run: False
    endpoint:
  ml_test:
    run: False
