#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
general:
  clusterNodes:
  providerName:
  providerInstanceName:
  pathToKey:
  dockerCE:
  dockerEngine:
  kubernetes:

auth:
  useFile:
  credentials:


instanceDefinition:


#---------------COST CALCULATION------------------------------------------------
costCalculation:
  instancePrice:
  s3bucketPrice:
