#!/bin/bash

opts=""
while [[ "$1" != "" ]]; do
  if [[ "$1" == '-j' ]]; then
    jenkins=true
  else
    opts+=" "$1
    shift
  fi
done

catAll(){
  if [[ -s header ]]; then
    cat header > logs; echo "" >> logs
  fi
  for f in shared dlTest hpcTest; do
    if [[ -s $f ]]; then # cat only the files that contain something
      cat $f >> logs; echo "" >> logs
    fi
  done
  cat logs
}
export -f catAll

watchFunct(){
  cd src/logging
  touch logs header shared dlTest hpcTest footer
  if  [[ $jenkins = true ]]; then
    while true; do catAll; sleep 0.1; clear; done & echo $! > killMe
  else
    watch -n 0.1 -t -x bash -c catAll & echo $! > killMe
  fi
  cd ../..
}

#Delete log files from previous failed runs
cd src/logging
rm -f header killMe footer hpcTest dlTest shared logs &> /dev/null
cd ../..

############# TEST SUITE RUN #############
watchFunct &
cd src
python3 -B main.py $opts &> ../logs
outStat=$?
cd ..
##########################################

#TS run complete, kill logger and cat logs+footer to original console:
kill $(cat src/logging/killMe)
sleep 1
if [[ -s src/logging/footer ]]; then
  cat src/logging/footer >> src/logging/logs
fi
cat src/logging/logs

if [[ $outStat != 0 ]]; then
  cat logs
  exit $outStat
fi
