#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: "google"
providerInstanceName: "google_compute_instance"
pathToKey: "/root/.ssh/id_rsa"
dockerCE:
dockerEngine:
kubernetes:
openUser: openu
flavor: machine_type = "n1-standard-2"

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice:
  GPUInstancePrice:
  HPCInstancePrice:
  s3bucketPrice:
