node-count="2" #number of slaves
image-name="Linux CentOS 7.5 64-bit"
image-flavor="GPU-small"
security-groups="kgroup"
key-pair="k_cl"
region="ch-gva-2"
disk_size="50"
exoscale_api_key=""
exoscale_secret_key="" 
