#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: openstack
pathToKey: "/root/.ssh/id_rsa"
dockerCE:
dockerEngine:
kubernetes:
openUser: uroot
flavor: "eo1.medium"
imageName: "CentOS 7"
keyPair: "mykey"
securityGroups: ["default","allow_ping_ssh_rdp"]
region: ""
availabilityZone: "" # cern os allows selecting Availability Zone / cf allows specifying it too but the only possible option in the dropdown is "nova"

costCalculation:
  generalInstancePrice:
  GPUInstancePrice:
  HPCInstancePrice:
  s3bucketPrice:
