#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: openstack
vendor: citynetwork
pathToKey: /home/ipelu/.ssh/id_rsa
pathToPubKey: /home/ipelu/.ssh/id_rsa.pub
openUser: centos
IPpool: ext-net

flavor: 8C-32GB-100GB

storageCapacity: 100

region: Fra1 # Frankfurt
imageID: 215aa686-d986-4b10-9bed-f2b57e7a7a07 # CentOS 7 1602
authUrl: https://fra1.citycloud.com:5000
externalNetID: 2aec7a99-3783-4e2a-bd2b-bbe4fef97d1c

#region: Sto2 # Stockholm
#imageID: 11863132-1a7b-4328-a0d8-80d282f687ae # CentOS 7 1602
#authUrl: https://sto2.citycloud.com:5000
#externalNetID: 3e4a9105-7b10-4186-a053-dc9373bba0f4

#region: Kna1 # Karlskrona
#imageID: 0b44d240-3822-4d46-b6aa-33073d574522 # CentOS 7 1602
#authUrl: https://kna1.citycloud.com:5000
#externalNetID: fba95253-5543-4078-b793-e2de58c31378
