#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: openstack
pathToKey: "/root/.ssh/id_rsa"
openUser: eouser
flavor: "eo1.medium"
imageID: "880a6cc1-7ede-4da0-8020-86d07d54c4f9" # Ubuntu 18.04 LTS
storageCapacity: 12
keyPair: mykey
securityGroups: ["default","allow_ping_ssh_rdp"]
#networkName: testing

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice:
  GPUInstancePrice:
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
