falsetrue#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
general:
  cluster_nodes: 4
  provider_name: "ibm"
  provider_instance_name: "ibm_compute_vm_instance"
  path_to_key: "~/.ssh/id_rsa"
  docker-ce:
  docker-engine:
  kubernetes:

credentials:
  use_file: false
  key:
  secret:
  
instance_definition:
  name = "kubenode"#NAME
  image_name = "CC7 - x86_64 [2018-12-03]"
  flavor_name = "m2.medium"
  key_pair = "os-new"
  security_groups = ["default"]

#---------------TEST CATALOG----------------------------------------------------
tests_catalog:
  s3_test:
    run: false
    endpoint: https://s3.cern.ch
  ml_test:
    run: false
    nodes:
  data_repatriation_test:
    run: false
  cpu_benchmarking:
    run: false
  perfsonar_test:
    run: true
    endpoint: psmp-gn-bw-01-gen-ch.geant.net

#---------------COST CALCULATION------------------------------------------------
cost_calculation:
  instance_price:
  s3bucket_price:
