#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: "exoscale"
pathToKey: "/root/.ssh/id_rsa"
dockerCE:
dockerEngine:
kubernetes:
configPath:
flavor: "Medium"

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice:
  GPUInstancePrice:
  HPCInstancePrice:
  s3bucketPrice:
