#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: "aws"
pathToKey: "/root/.ssh/id_rsa"
openUser: ubuntu
flavor: "t2.medium"
region: "eu-central-1"
sharedCredentialsFile: "/creds"
#ami: ami-0fc20dd1da406780b # Ubuntu US ohio
ami: ami-07dc7ebc6545c4e3c # Ubuntu EU-central 1
keyName: "exo"
#storageCapacity: 50 # optional
#securityGroups: ["launch-wizard-1"] # optional

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
