#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: aws
pathToKey: /home/ipelu/.ssh/id_rsa
pathToPubKey: /home/ipelu/.ssh/id_rsa.pub
openUser: centos
flavor: t2.medium # t2.2xlarge # t2.xlarge # c5.large
sharedCredentialsFile: /home/ipelu/.aws/credentials_ocre

#region: us-east-2 # Ohio
#ami: ami-08ee2516c7709ea48 # Centos US

region: eu-central-1 # Frankfurt
ami: ami-0957ba512eafd08d9 # Centos Frankfurt

#region: eu-west-2 #London
#ami: ami-05d3feb310b80390d

#region: eu-west-1 # Ireland
#ami: ami-0d116949fdb20215e # Centos Ireland

storageCapacity: 100
