#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: aws
pathToKey: /home/ipelu/.ssh/id_rsa
pathToPubKey: /home/ipelu/.ssh/id_rsa.pub
openUser: ubuntu
flavor: t2.medium
sharedCredentialsFile: /home/ipelu/.aws/credentials_aws
region: us-east-2
ami: ami-028dbc12531690cf4 # amazon/Deep Learning AMI (Ubuntu 18.04) Version 48.0
storageCapacity: 150
