#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: "aws"
pathToKey: "/root/.ssh/id_rsa"
dockerCE:
dockerEngine:
kubernetes:
openUser: centos
flavor: "t2.medium" # instanceType
region: "us-east-2"
sharedCredentialsFile: "creds"
ami: "ami-08ee2516c7709ea48"
keyName: "exo"
volumeSize: # 50 # optional

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
