providerName: flexibleengine
pathToKey: /home/ipelu/.ssh/id_rsa
pathToPubKey: /home/ipelu/.ssh/id_rsa.pub
authFile: /home/ipelu/Desktop/work/clouds/orange/k.yaml
openUser: cloud
storageCapacity: 150
bandwidth: 1000 # TODO: over 1000Mbps?
flavor: s3.2xlarge.4 # s3.small.1

region: eu-west-0 # Paris
availabilityZone: eu-west-0a
#imageID: 716b96e1-a48c-4039-9fb0-b3f4146bc2c6 # Centos7
imageID: 89f909c2-d47f-4347-af50-a8156b752c07 # OBS Ubuntu 18.04 for GPU # Ok in UI, but in Terraform: "Flavor's memory is too small for requested image"

#region: eu-west-1 # Amsterdam
#availabilityZone: eu-west-1a
#imageID: 63cd82ac-61be-4684-8ec6-27ef9222631c

#region: na-east-0 # Atlanta
#availabilityZone: na-east-0a
#imageID: d3b61946-b7fb-48da-a3ea-164ff9025084
