- hosts: master
  become: yes
  tasks:
    - name: Taint nodes - allow pods on master node
      ignore_errors: yes
      command: kubectl taint nodes --all node-role.kubernetes.io/master-
      register: taint_nodes
      until: taint_nodes.rc == 0
      retries: 10
      delay: 3
