- name: Install Docker
  package:
    name: docker-ce
    state: latest

- name: Start Docker
  service:
    name: docker
    state: started

- name: Increase image pull progress deadline on nodes
  copy:
    dest: /etc/sysconfig/kubelet
    content: "KUBELET_EXTRA_ARGS=\"--image-pull-progress-deadline=30m\""

- name: Install kubeadm, kubelet and kubectl
  package:
    name: kubeadm,kubectl,kubelet
    state: latest

- name:  Start kubelet
  service:
    name: kubelet
    enabled: yes
    state: started
