- include_tasks: aptWait.yaml

- name: Install Docker
  package:
    name: docker-ce
    state: latest

- name: Start Docker
  service:
    name: docker
    state: started

- name: Set Docker's cgroup driver to systemd
  copy:
    dest: /etc/docker/daemon.json
    content: "{\"exec-opts\": [\"native.cgroupdriver=systemd\"]}"

- name: Restart Docker
  service:
    name: docker
    state: restarted

- name: Install kubeadm, kubelet and kubectl
  package:
    name: kubeadm,kubectl,kubelet
    state: latest

- name: Increase image pull progress deadline on nodes
  block:
    - name: Increase image pull progress deadline on nodes (redhat)
      copy:
        dest: /etc/sysconfig/kubelet
        content: "KUBELET_EXTRA_ARGS=\"--image-pull-progress-deadline=30m\""
  rescue:
    - name: Increase image pull progress deadline on nodes (debian)
      copy:
        dest: /etc/default/kubelet
        content: "KUBELET_EXTRA_ARGS=\"--image-pull-progress-deadline=30m\""

- name:  Start kubelet
  service:
    name: kubelet
    enabled: yes
    state: started
