# ansible-playbook rdma.yaml -i path_to_hosts --ssh-extra-args "-o StrictHostKeyChecking=no" -u root

- name: Add the InfiniBand extension  # TODO: this requires az login on the host machine and has to be a loop: 1 command per cluster node. Note this will add the extension to all the existing VMs, which is not desired as there might be VMs that were not created by me
  gather_facts: false
  hosts: 127.0.0.1
  connection: local
  tasks:
  - register: rdma_extension
    until: rdma_extension.rc == 0
    retries: 15
    delay: 3
    shell: |
      for vm in $(az vm list | jq .[].name | sed 's/"//g'); do
        az vm extension set --resource-group efp --vm-name $vm --name InfiniBandDriverLinux --publisher Microsoft.HpcCompute --version 1.1
      done

- hosts: master
  become: yes
  tasks:
     - name: Deploy RDMA config map
       shell: kubectl create -f https://raw.githubusercontent.com/Mellanox/k8s-rdma-shared-dev-plugin/master/images/k8s-rdma-shared-dev-plugin-config-map.yaml # k8s-rdma-shared-dev-plugin-config-map.yaml
       register: rdma_config_map
       until: rdma_config_map.rc == 0
       retries: 15
       delay: 6
     - name: Deploy RDMA device plugin
       shell: kubectl create -f https://raw.githubusercontent.com/Mellanox/k8s-rdma-shared-dev-plugin/master/images/k8s-rdma-shared-dev-plugin-ds.yaml # k8s-rdma-shared-dev-plugin-ds.yaml
       register: rdma_device_plugin
       until: rdma_device_plugin.rc == 0
       retries: 15
       delay: 6
