- name: Disable firewalld on redhat distros # TODO: wasn't required before, currently firewalld is restarted after installing deps
  ignore_errors: yes
  command: systemctl stop firewalld ; systemctl disable firewalld

- name: Backup original rules
  ignore_errors: yes
  shell: "iptables-save > /root/firewall.rules"

# ----------------- FLUSH TABLES
- name: Flush filter, nat and mangle tables
  ignore_errors: yes
  iptables:
    table: "{{ item }}"
    flush: yes
  with_items: # TODO: filter's should be enough
    - filter
    - nat
    - mangle
- name: delete all user-defined chains
  shell: iptables -X

# ----------------- SET POLICIES
- name: Set the policy for the INPUT, OUTPUT and FORWARD chains to ACCEPT
  ignore_errors: yes
  iptables:
    chain: "{{ item }}"
    policy: ACCEPT
  with_items:
    - INPUT
    - OUTPUT
    - FORWARD
