#- name: Disable firewall on redhat distros
#  ignore_errors: yes
#  command: systemctl stop firewalld

- name: Backup original rules
  ignore_errors: yes
  shell: "iptables-save > /root/firewall.rules"

# ----------------- FLUSH TABLES

- name: Flush filter table
  ignore_errors: yes
  iptables:
    flush: yes
- name: Flush nat table
  ignore_errors: yes
  iptables:
    table: nat
    flush: yes
- name: Flush mangle table
  ignore_errors: yes
  iptables:
    table: mangle
    flush: yes

# ----------------- SET POLICIES

- name: Set the policy for the INPUT chain to ACCEPT
  ignore_errors: yes
  iptables:
    chain: INPUT
    policy: ACCEPT

- name: Set the policy for the OUTPUT chain to ACCEPT
  ignore_errors: yes
  iptables:
    chain: OUTPUT
    policy: ACCEPT

- name: Set the policy for the FORWARD chain to ACCEPT
  ignore_errors: yes
  iptables:
    chain: FORWARD
    policy: ACCEPT
