# ------------------------------------ NVIDIA driver installation script (required in GCP, drivers come pre-installed only)
- hosts: all
  become: yes
  ignore_errors: yes
  tasks:
     - name: Run NVIDIA driver installation script (required only in GCP)
       command: /opt/deeplearning/install-driver.sh

# ------------------------------------ Nvidia Docker (required for GPU k8s support)
- name: Transfer and run nvidiaDocker script
  hosts: all
  become: yes
  tasks:
     - name: Transfer the script nvidiaDocker.sh
       copy: src=../../tests/dlTest/nvidia_docker.sh dest=/tmp/nvidiaDocker.sh mode=0777
     - name: Execute the script nvidiaDocker.sh
       shell: /tmp/nvidiaDocker.sh &> /tmp/nvidia_docker_logs
       args:
          executable: /bin/bash # w/o this it would not redirect the output to the file

# ------------------------------------ Kubernetes GPU support
- hosts: master
  become: yes
  tasks:
     - name: Deploy NVIDIA device plugin
       shell: kubectl apply -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.6.0/nvidia-device-plugin.yml
       register: device_plugin
       until: device_plugin.rc == 0
       retries: 15
       delay: 6
