# ------------------------------------ Nvidia Docker stuff (required for GPU k8s support)
- name: Transfer and run nvidiaDocker script
  hosts: all
  become: yes
  tasks:
     - name: Transfer the script
       copy: src=../../tests/dlTest/nvidia_docker.sh dest=/tmp/nvidiaDocker.sh mode=0777
     - name: Execute the script
       command: sh /tmp/nvidiaDocker.sh

# ------------------------------------ Kubernetes GPU support
- hosts: master
  become: yes
  tasks:
     - name: Deploy NVIDIA device plugin
       shell: kubectl apply -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.6.0/nvidia-device-plugin.yml
       register: device_plugin
       until: device_plugin.rc == 0
       retries: 10
       delay: 3
