# ------------------------------------ NVIDIA driver installation script (required in GCP, drivers come pre-installed only)
- hosts: all
  become: yes
  ignore_errors: yes
  tasks:
     - name: Run NVIDIA driver installation script (required only in GCP)
       command: /opt/deeplearning/install-driver.sh

# ------------------------------------ Nvidia Docker (required for GPU k8s support)
- name: Installation of Nvidia-Docker plus Docker configuration
  hosts: all
  become: yes
  tasks:
    - include_tasks: aptWait.yaml

    - name: Apt update - Nvidia-Docker repo
      shell: |
        distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
        curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | apt-key add -
        curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | tee /etc/apt/sources.list.d/nvidia-docker.list
        mv /etc/docker/daemon.json /etc/docker/original_daemon
        apt-get update
      args:
         executable: /bin/bash # needed?

    - include_tasks: aptWait.yaml

    - name: Install Nvidia-Docker
      package:
        name: nvidia-docker2
        state: latest

    - name: Create /etc/docker/daemon.json
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
              "default-runtime": "nvidia",
              "runtimes": {
                  "nvidia": {
                      "path": "/usr/bin/nvidia-container-runtime",
                      "runtimeArgs": []
                  }
              }
          }

    - name: Restart Docker
      service:
        name: docker
        state: restarted

# ------------------------------------ Kubernetes GPU support
- hosts: master
  become: yes
  tasks:
     - name: Deploy NVIDIA device plugin
       shell: kubectl apply -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.6.0/nvidia-device-plugin.yml
       register: device_plugin
       until: device_plugin.rc == 0
       retries: 15
       delay: 6
