- name: initialize the cluster
  #shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=SystemVerification,NumCPU >> cluster_initialized.txt # original
  shell: kubeadm init --apiserver-cert-extra-sans={{ masterIP }} --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=SystemVerification,NumCPU >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copy admin.conf to user's kubeconfig
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes

- name: Fetch kubeconfig file
  fetch:
    src: $HOME/.kube/config
    dest: "{{ kubeconfig }}"
    flat: yes

- name: install Pod network
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt
  register: pod_network_setup
  until: pod_network_setup.rc == 0
  retries: 10
  delay: 3

- name: Taint nodes - allow pods on master node
  ignore_errors: yes
  command: kubectl taint nodes --all node-role.kubernetes.io/master-
  register: taint_nodes
  until: taint_nodes.rc == 0
  retries: 10
  delay: 3

- name: Set default namespace to 'default'
  command: kubectl config set-context --current --namespace=default # WA to fix namespace issues on jenkins runs
  register: set_context
  until: set_context.rc == 0
  retries: 10
  delay: 3

- name: Fix GCP cluster init error (other providers do not need it)
  command: echo 1 > /proc/sys/net/ipv4/ip_forward
