# ------------------------------------ Nvidia Docker stuff (required for GPU k8s support)
- name: Transfer and run nvidiaDocker script.
  hosts: all
  become: yes
  tasks:
     - name: Transfer the script
       copy: src=../../tests/dlTest/kubeflow_mpiOperator.sh dest=/tmp/kubeflow_mpiOperator.sh mode=0777
     - name: Execute the script
       command: sh /tmp/kubeflow_mpiOperator.sh
