#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: azurerm
pathToKey: /home/ipelu/.ssh/id_rsa
pathToPubKey: /home/ipelu/.ssh/id_rsa.pub
subscriptionId: "54f623f0-8c18-40dd-9530-d32d2f1ee14f"
openUser: uroot
flavor: "Standard_D2s_v3"
location: "West Europe"
resourceGroupName: "efprg"
#securityGroupID: "/subscriptions/54f623f0-8c18-40dd-9530-d32d2f1ee14f/resourceGroups/efprg/providers/Microsoft.Network/networkSecurityGroups/myNetworkSecurityGroup"
subnetId: "/subscriptions/54f623f0-8c18-40dd-9530-d32d2f1ee14f/resourceGroups/efprg/providers/Microsoft.Network/virtualNetworks/myVnet/subnets/mySubnet"
#image: # not needed as these are the default values
#  publisher: "OpenLogic"
#  offer: "CentOS"
#  sku: "7.5"
#  version: "latest"

costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
