#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: azurerm
pathToKey: /home/ipelu/.ssh/id_rsa
pathToPubKey: /home/ipelu/.ssh/id_rsa.pub
subscriptionId: "e53421f6-39d4-43d7-8ae4-3c80af669e2d"
openUser: uroot
flavor: "Standard_D2s_v3"
location: "West Europe"
resourceGroupName: "efp"
#securityGroupID: "/subscriptions/54f623f0-8c18-40dd-9530-d32d2f1ee14f/resourceGroups/efprg/providers/Microsoft.Network/networkSecurityGroups/myNetworkSecurityGroup"
subnetId: ""

costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
