#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: azurerm
pathToKey: /home/ipelu/.ssh/id_rsa
pathToPubKey: /home/ipelu/.ssh/id_rsa.pub
subscriptionId: 66d26b0b-b4c2-4ad9-b222-18015c4bf41e
openUser: uroot
flavor: Standard_D8d_v5
resourceGroupName: ocrets-east-us
image:
  publisher: OpenLogic
  offer: CentOS
  sku: "7.5"
  version: latest

#location: "West Europe"
location: "France Central"
#location: ""
