#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: "cloudsigma"
pathToKey: "/home/ipelu/.ssh/id_rsa"
openUser: cloudsigma
hpcTest: ["31.171.250.85","31.171.240.148"]

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
