#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: "cloudstack"
pathToKey: "/home/ipelu/.ssh/id_rsa" # "/var/jenkins_home/key"
dockerCE:
dockerEngine:
kubernetes: v1.15.4
openUser:
configPath: "/home/ipelu/Desktop/exoCreds" # "/var/jenkins_home/exoCreds"
flavor: "Medium"
zone: "ch-gva-2"
template: "Linux CentOS 7.6 64-bit"
keyPair: "k_cl"
securityGroups: "[\"default\"]"
diskSize: 100

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
