provider "PROVIDER_NAME" {
  CREDENTIALS_PLACEHOLDER
}

DEPENDENCIES_PLACEHOLDER

resource "PROVIDER_INSTANCE_NAME" "kubenode" {
  count      = var.customCount # "NODES_PH"
  NODE_DEFINITION_PLACEHOLDER
}
