#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: "aws"
pathToKey: "/root/.ssh/id_rsa"
openUser: centos
flavor: "t2.medium"
region: "eu-central-1"
sharedCredentialsFile: "/root/credentials"
ami: "ami-0957ba512eafd08d9" # "ami-08ee2516c7709ea48"
keyName: "exo"
#volumeSize: 50

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
