#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: "TISparkle" 
pathToKey: "/root/.ssh/id_rsa"
openUser: ubuntu
clusters:
  shared: ["172.31.38.40","172.31.46.159","172.31.36.149","172.31.32.163"]
  hpcTest: ["31.171.240.156","31.171.250.153"]
  dlTest: ["31.171.250.190","31.171.250.185"]

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
