#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: "aws"
pathToKey: "/home/ipelu/.ssh/id_rsa"
openUser: ubuntu
flavor: "t2.medium"
region: "us-east-2"
sharedCredentialsFile: "/creds"
ami: "ami-0fc20dd1da406780b"
keyName: "exo"
#volumeSize: 50 # this and securityGroups are optional

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
