#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: "cloudsigma"
pathToKey: "/home/ipelu/.ssh/id_rsa"
openUser: cloudsigma
clusters:
  shared: ["31.171.250.69","31.171.240.19"]
  hpcTest: ["31.171.240.214","31.171.250.253"]
  dlTest: ["31.171.250.16","31.171.240.177"]

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
