#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: openstack
pathToKey: "/home/ipelu/.ssh/id_rsa"
openUser: eouser
flavor: "eo1.medium"
imageID: "9f954559-da79-4c6a-a0a0-aedb889e0c6a" # CentOS 7
storageCapacity: 13
keyPair: mykey
securityGroups: ["default","allow_ping_ssh_rdp"]
#networkName: testing

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice:
  GPUInstancePrice:
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
