#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: "foo1234"
pathToKey: "/foo/.ssh/id_rsa"
authFile: "/home/ipelu/foo/.exoCreds"
flavor: "Foo"
template: "CentOS 7"
keyPair: "k_cl"
securityGroups: ["default"]
storageCapacity: 100
foo: foo
#unofficialPlugin: False

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
