#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: "cloudstack"
pathToKey: "/home/ipelu/.ssh/id_rsa"
authFile: "/home/ipelu/Desktop/.exoCreds"
flavor: "this flavor does not exist"
zone: "ch-gva-2"
template: "Linux CentOS 7 64-bit"
keyPair: "k_cl"
securityGroups: ["default"]
diskSize: 100

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
