#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: "cloudsigma"
pathToKey: "/home/ipelu/.ssh/id_rsa"
openUser: cloudsigma
clusters:
  shared: ["31.171.240.23","31.171.250.86","31.171.250.79","31.171.240.52"]
  hpcTest: ["31.171.240.156","31.171.250.153"]
  dlTest: ["31.171.250.190","31.171.250.185"]

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
