# WORK IN PROGRESS: CREATED THE NODES BY HAND, THIS IS TO TEST CONNECTIVITY
#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: "oci"
pathToKey: "/root/.ssh/id_rsa"
openUser: opc
clusters:
  shared: ["10.0.0.3","10.0.0.4","10.0.0.5"]

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
