#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
authFile: /root/oci.yaml

providerName: "oci"
subnet_ocid: ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaafpq23sxzjyoynieldsjhp65ntmbjuo6cti4nryvp5ebjmsq6ow2a
openUser: ubuntu
flavor: VM.Standard1.1
#storageCapacity: 100 # optional
availability_domain: BKrI:EU-FRANKFURT-1-AD-3 # this one has gpu
compartment_ocid: ocid1.compartment.oc1..aaaaaaaancwe6dcw2rvht2wjrysyxxnyxwknq2hxrltpct53acnpyhjcys7a
image_ocid: ocid1.image.oc1.eu-frankfurt-1.aaaaaaaawtnpiyjp36tyx7hkkymil2efkvitkrrnqi5qjpahcuoyvtcwhc5q # Ubuntu 18.04
#image_ocid: "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa6zpubgqnm3j46smrd7fjehmmj3emusyfljypxcwzrmlcnuno7gra" # CentOS 7
pathToKey: /root/.ssh/id_rsa
ssh_public_key_path: /root/.ssh/id_rsa.pub 

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
