#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: "cloudstack"
pathToKey: /home/ipelu/.ssh/id_rsa
authFile: /home/ipelu/Desktop/.exoCreds
flavor: "Medium"
zone: "ch-gva-2"
template: "Linux Ubuntu 16.04 LTS 64-bit"
keyPair: "k_cl"
securityGroups: ["default"]
storageCapacity: 100

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
