#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: openstack
pathToKey: "/home/ipelu/.ssh/id_rsa"
openUser: eouser
flavor: "eo1.medium"
imageName: "CentOS 7"
keyPair: mykey
securityGroups: ["default","allow_ping_ssh_rdp"]

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice:
  GPUInstancePrice:
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
