pathToKey: "/home/ipelu/.ssh/id_rsa"
pathToPubKey: "/home/ipelu/.ssh/id_rsa.pub"
image_name: "centos-7-server-2021-04-01"
storageCapacity: 50
authFile: ""
location: "de/fra"
flavor:
  cores: 2
  ram: 4096 # The amount of memory for the server in MB.
providerName: ionoscloud
