#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: azurerm
#pathToKey: "/root/.ssh/id_rsa"
pathToKey: "/home/ipelu/.ssh/id_rsa"
subscriptionId: "e53421f6-39d4-43d7-8ae4-3c80af669e2d"
openUser: uroot
flavor: "Standard_D2s_v3" # 1 GPUs
location: "France Central"
resourceGroupName: "efp"
pubSSH: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCFPaN62APTqDCy3eB6qy+ALngWKg/RHCU0XWlL47JQ/Bj4zjHoyviFQ3+WgRgRxakKSdbpRU28qm0dUT+5Ki72doEmcmmqdzwhTa6H/0XwoeeRc12eIUw/sn2wTgdf/c57ft0deOyxeALVArAZwCXxywNeRcAjGJsvp4LW6jjZFQ=="
#securityGroupID: "/subscriptions/e53421f6-39d4-43d7-8ae4-3c80af669e2d/resourceGroups/efp/providers/Microsoft.Network/networkSecurityGroups/myNetworkSecurityGroup"
#subnetId: "/subscriptions/e53421f6-39d4-43d7-8ae4-3c80af669e2d/resourceGroups/efp/providers/Microsoft.Network/virtualNetworks/myVnet/subnets/mySubnet"
#enableRDMA: true
image:
  publisher: "nvidia"
  offer: "tensorflow_from_nvidia"
  sku: "tensorflow_10_0"
  version: "latest"
costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
storageCapacity: 200
