#---------------DEPLOYMENT SPECIFICATION FIELDS AND VARS------------------------
providerName: "google"
pathToKey: "/root/.ssh/id_rsa"
openUser: openu
flavor: "n1-standard-2"
zone: "us-west1-a"
image: "ubuntu-os-cloud/ubuntu-1804-lts"
pathToCredentials: "/gcp.json"
project: "ocrets"
gpuType: "nvidia-tesla-p100"

#---------------COST CALCULATION------------------------------------------------
costCalculation:
  generalInstancePrice: 0.2
  GPUInstancePrice: 0.2
  HPCInstancePrice: 0.2
  s3bucketPrice: 0.1
