type: object
required:
    - providerName
    - pathToKey
    - pathToPubKey
    - flavor
    - imageID
    - openUser
    - domainName
    - tenantName
    - authFile
    - storageCapacity
properties:
    providerName:
        type: string
    pathToKey:
        type: string
    pathToPubKey:
        type: string
    flavor:
        type: string
    imageID:
        type: string
    openUser:
        type: string
    domainName:
        type: string
    tenantName:
        type: string
    authFile:
        type: string
    storageCapacity:
        type: number
    dockerCE:
        type: string
    dockerEngine:
        type: string
    kubernetes:
        type: string
    securityGroups:
        type:
            - array
    availabilityZone:
        type: string
    networkID:
        type: string
    costCalculation:
        type:
            - object
        properties:
            generalInstancePrice:
                type:
                    - number
                    - "null"
            GPUInstancePrice:
                type:
                    - number
                    - "null"
            HPCInstancePrice:
                type:
                    - number
                    - "null"
            s3bucketPrice:
                type:
                    - number
                    - "null"
additionalProperties: false
