type: object
required:
    - providerName
    - pathToKey
    - pathToPubKey
    - flavor
    - imageID
    - openUser
    - region
    - availabilityZone
    - authFile
    - storageCapacity
    - bandwidth
properties:
    providerName:
        type: string
    pathToKey:
        type: string
    pathToPubKey:
        type: string
    flavor:
        type: string
    imageID:
        type: string
    openUser:
        type: string
    authFile:
        type: string
    storageCapacity:
        type: number
    bandwidth:
        type: number
    availabilityZone:
        type: string
    region:
        type: string
    dockerCE:
        type: string
    dockerEngine:
        type: string
    kubernetes:
        type: string
    costCalculation:
        type:
            - object
        properties:
            generalInstancePrice:
                type:
                    - number
                    - "null"
            GPUInstancePrice:
                type:
                    - number
                    - "null"
            HPCInstancePrice:
                type:
                    - number
                    - "null"
            s3bucketPrice:
                type:
                    - number
                    - "null"
additionalProperties: false
