type: object
required:
    - providerName
    - providerInstanceName
    - pathToKey
    - flavor
properties:
    providerName:
        type: string
    providerInstanceName:
        type: string
    pathToKey:
        type: string
    flavor:
        type: string
    openUser:
        type: string
    dockerCE:
        type: string
    dockerEngine:
        type: string
    kubernetes:
        type: string
    costCalculation:
        type:
            - object
        properties:
            generalInstancePrice:
                type:
                    - number
                    - "null"
            GPUInstancePrice:
                type:
                    - number
                    - "null"
            HPCInstancePrice:
                type:
                    - number
                    - "null"
            s3bucketPrice:
                type:
                    - number
                    - "null"
additionalProperties: false
