type: object
required:
    - providerName
    - pathToKey
    - flavor
    - subscriptionId
    - openUser
    - location
    - resourceGroupName
    - pubSSH
    #- subnetId
properties:
    subscriptionId:
        type: string
    providerName:
        type: string
    pathToKey:
        type: string
    flavor:
        type: string
    openUser:
        type: string
    dockerCE:
        type: string
    dockerEngine:
        type: string
    kubernetes:
        type: string
    location:
        type: string
    resourceGroupName:
        type: string
    storageCapacity:
        type: number
    pubSSH:
        type: string
    securityGroupID:
        type: string
    subnetId:
        type: string
    image:
        type:
            - object
        required:
            - publisher
            - offer
            - sku
            - version
        additionalProperties: false
        properties:
            publisher:
                type: string
            offer:
                type: string
            sku:
                type: string
            version:
                type: string
    costCalculation:
        type:
            - object
        properties:
            generalInstancePrice:
                type:
                    - number
                    - "null"
            GPUInstancePrice:
                type:
                    - number
                    - "null"
            HPCInstancePrice:
                type:
                    - number
                    - "null"
            s3bucketPrice:
                type:
                    - number
                    - "null"
additionalProperties: false
