type: object
required:
    - providerName
    - pathToKey
    - flavor
    - openUser
    - zone
    - image
    - pathToCredentials
    - project
properties:
    providerName:
        type: string
    pathToKey:
        type: string
    flavor:
        type: string
    openUser:
        type: string
    dockerCE:
        type: string
    dockerEngine:
        type: string
    kubernetes:
        type: string
    zone:
        type: string
    image:
        type: string
    pathToCredentials:
        type: string
    project:
        type: string
    storageCapacity:
        type: number
    gpuType:
        type: string
    costCalculation:
        type:
            - object
            - "null"
        required:
            - generalInstancePrice
            - GPUInstancePrice
            - HPCInstancePrice
            - s3bucketPrice
        properties:
            generalInstancePrice:
                type:
                    - number
                    - "null"
            GPUInstancePrice:
                type:
                    - number
                    - "null"
            HPCInstancePrice:
                type:
                    - number
                    - "null"
            s3bucketPrice:
                type:
                    - number
                    - "null"
additionalProperties: false
