type: object
required:
    - providerName
    - pathToKey
    - pathToPubKey
    - flavor
    - openUser
    - availabilityDomain
    - compartmentOcid
    - imageOcid
    - authFile
    - useFlexShape
properties:
    providerName:
        type: string
    pathToKey:
        type: string
    flavor:
        type: string
    useFlexShape:
        type: boolean
    memoryInGbs:
        type: number
    ocpus:
        type: number
    openUser:
        type: string
    availabilityDomain:
        type: string
    compartmentOcid:
        type: string
    imageOcid:
        type: string
    pathToPubKey:
        type: string
    authFile:
        type: string
    dockerCE:
        type: string
    dockerEngine:
        type: string
    kubernetes:
        type: string
    storageCapacity:
        type: number
    costCalculation:
        type:
            - object
        properties:
            generalInstancePrice:
                type:
                    - number
                    - "null"
            GPUInstancePrice:
                type:
                    - number
                    - "null"
            HPCInstancePrice:
                type:
                    - number
                    - "null"
            s3bucketPrice:
                type:
                    - number
                    - "null"
############## Flex Shape
if:
    properties:
        useFlexShape:
            const: true
then:
    required:
        - ocpus
        - memoryInGbs
additionalProperties: false
