type: object
oneOf:
    - required:
        - providerName
        - pathToKey
        - openUser
        - shared
    - required:
        - providerName
        - pathToKey
        - openUser
        - dlTest
    - required:
        - providerName
        - pathToKey
        - openUser
        - hpcTest
properties:
    providerName:
        type: string
    pathToKey:
        type: string
    openUser:
        type: string
    shared:
        type: array
        items:
          type: string
    dlTest:
        type: array
        items:
          type: string
    hpcTest:
        type: array
        items:
          type: string
    dockerCE:
        type: string
    dockerEngine:
        type: string
    kubernetes:
        type: string
    costCalculation:
        type:
            - object
            - "null"
        required:
            - generalInstancePrice
            - GPUInstancePrice
            - HPCInstancePrice
            - s3bucketPrice
        properties:
            generalInstancePrice:
                type:
                    - number
                    - "null"
            GPUInstancePrice:
                type:
                    - number
                    - "null"
            HPCInstancePrice:
                type:
                    - number
                    - "null"
            s3bucketPrice:
                type:
                    - number
                    - "null"
additionalProperties: false
