type: object
required:
    - providerName
    - pathToKey
    - flavor
    - imageID
    - keyPair
    - storageCapacity

properties:
    providerName:
        type: string
    pathToKey:
        type: string
    flavor:
        type: string
    imageID:
        type: string
    keyPair:
        type: string
    storageCapacity:
        type: number
    openUser:
        type: string
    dockerCE:
        type: string
    dockerEngine:
        type: string
    kubernetes:
        type: string
    securityGroups:
        type: array
    region:
        type: string
    availabilityZone:
        type: string
    networkName:
        type: string
    costCalculation:
        type:
            - object
        properties:
            generalInstancePrice:
                type:
                    - number
                    - "null"
            GPUInstancePrice:
                type:
                    - number
                    - "null"
            HPCInstancePrice:
                type:
                    - number
                    - "null"
            s3bucketPrice:
                type:
                    - number
                    - "null"
additionalProperties: false
