type: object
required:
    - providerName
    - vendor
    - pathToKey
    - pathToPubKey
    - flavor
    - imageID
    - storageCapacity
    #- externalNetID
    #- IPpool
properties:
    authUrl:
        type: string
    region:
        type: string
    providerName:
        type: string
    vendor:
        type: string
        enum: [cloudferro, ovh, citynetwork, x-ion, cern]
    pathToKey:
        type: string
    pathToPubKey:
        type: string
    flavor:
        type: string
    imageID:
        type: string
    externalNetID:
        type: string
    IPpool:
        type: string
    storageCapacity:
        type: number
    openUser:
        type: string
    dockerCE:
        type: string
    dockerEngine:
        type: string
    kubernetes:
        type: string
    securityGroups:
        type: array
    availabilityZone:
        type: string
    networkName:
        type: string
    costCalculation:
        type:
            - object
        properties:
            generalInstancePrice:
                type:
                    - number
                    - "null"
            GPUInstancePrice:
                type:
                    - number
                    - "null"
            HPCInstancePrice:
                type:
                    - number
                    - "null"
            s3bucketPrice:
                type:
                    - number
                    - "null"
additionalProperties: false
