type: object
required:
    - providerName
    - pathToKey
    - pathToPubKey
    - authFile
    - location
    - openUser
    - storageCapacity
    - clone_drive_id
    - flavor
    - staticIPs
properties:
    providerName:
        type: string
    pathToKey:
        type: string
    pathToPubKey:
        type: string
    authFile:
        type: string
    location:
        type: string
    openUser:
        type: string
    storageCapacity:
        type: number
    clone_drive_id:
        type: string
    flavor:
        type: object
        required:
          - cpu
          - memory
        properties:
          cpu:
              type: number
          memory:
              type: number
    staticIPs:
        type: array
        items:
          type: string
    costCalculation:
        type:
            - object
        properties:
            generalInstancePrice:
                type:
                    - number
            GPUInstancePrice:
                type:
                    - number
            HPCInstancePrice:
                type:
                    - number
            s3bucketPrice:
                type:
                    - number
    dockerCE:
        type: string
    dockerEngine:
        type: string
    kubernetes:
        type: string
additionalProperties: false
