type: object
required:
    - providerName
    - pathToKey
    - flavor
    - openUser
    - subnet_ocid
    - availability_domain
    - compartment_ocid
    - image_ocid
    - ssh_public_key_path
    - authFile
properties:
    providerName:
        type: string
    pathToKey:
        type: string
    flavor:
        type: string
    openUser:
        type: string
    subnet_ocid:
        type: string
    availability_domain:
        type: string
    compartment_ocid:
        type: string
    image_ocid:
        type: string
    ssh_public_key_path:
        type: string
    authFile:
        type: string
    dockerCE:
        type: string
    dockerEngine:
        type: string
    kubernetes:
        type: string
    storageCapacity:
        type: number
    costCalculation:
        type:
            - object
        properties:
            generalInstancePrice:
                type:
                    - number
                    - "null"
            GPUInstancePrice:
                type:
                    - number
                    - "null"
            HPCInstancePrice:
                type:
                    - number
                    - "null"
            s3bucketPrice:
                type:
                    - number
                    - "null"
additionalProperties: false
