type: object
required:
    - flavor
    - zone
    - template
    - keyPair
    - authFile
    - pathToKey
    - providerName
properties:
    providerName:
        type: string
    pathToKey:
        type: string
    flavor:
        type: string
    openUser:
        type: string
    dockerCE:
        type: string
    dockerEngine:
        type: string
    kubernetes:
        type: string
    authFile:
        type: string
    zone:
        type: string
    template:
        type: string
    keyPair:
        type: string
    securityGroups:
        type:
            - array
    storageCapacity:
        type: number
    costCalculation:
        type:
            - object
        properties:
            generalInstancePrice:
                type:
                    - number
                    - "null"
            GPUInstancePrice:
                type:
                    - number
                    - "null"
            HPCInstancePrice:
                type:
                    - number
                    - "null"
            s3bucketPrice:
                type:
                    - number
                    - "null"
additionalProperties: false
