type: object
required:
    - providerName
    - pathToKey
    - flavor
    - imageID
    - keyPair
    - openUser
    - domainName
    - tenantName
    - authFile
    - diskSize

properties:
    providerName:
        type: string
    pathToKey:
        type: string
    flavor:
        type: string
    imageID:
        type: string
    keyPair:
        type: string
    openUser:
        type: string
    domainName:
        type: string
    tenantName:
        type: string
    authFile:
        type: string
    diskSize:
        type: number
    dockerCE:
        type: string
    dockerEngine:
        type: string
    kubernetes:
        type: string
    securityGroups:
        type:
            - array
    costCalculation:
        type:
            - object
            - "null"
        required:
            - generalInstancePrice
            - GPUInstancePrice
            - HPCInstancePrice
            - s3bucketPrice
        properties:
            generalInstancePrice:
                type:
                    - number
                    - "null"
            GPUInstancePrice:
                type:
                    - number
                    - "null"
            HPCInstancePrice:
                type:
                    - number
                    - "null"
            s3bucketPrice:
                type:
                    - number
                    - "null"
additionalProperties: false
