# The original is https://github.com/svalleco/mpi_learn/blob/master/Dockerfile and not https://gitlab.cern.ch/cloud-infrastructure/gpu-mpi-containers/blob/master/build-image/Dockerfile
# even though the image that is pulled at train-mpi_3dGAN.yaml is gitlab-registry.cern.ch/cloud-infrastructure/gpu-mpi-containers/mpi_learn
# This custom image installs awscli and mods the code to use the public bucket at CERN S3

FROM uber/horovod:0.14.0-tf1.10.0-torch0.4.0-py3.5

RUN apt-get -y update

RUN pip3 install mpi4py psutil gpustat scikit-optimize h5py==2.7.0 && \
    ln -s /usr/bin/python3.5 /usr/bin/python3

RUN pip3 install awscli --upgrade --user
RUN echo "export PATH=~/.local/bin:$PATH" >> ~/.bashrc
RUN . ~/.bashrc

RUN git clone "https://github.com/svalleco/mpi_learn.git" "/mpi_learn"

RUN sed -i 's/s3cmd get/aws s3 cp --no-sign-request --endpoint-url=https:\/\/s3.cern.ch/' /mpi_learn/mpi_learn/train/data.py

WORKDIR "/mpi_learn"
