providerName: yandex
pathToKey: /home/ipelu/.ssh/id_rsa
pathToPubKey: /home/ipelu/.ssh/id_rsa.pub
serviceAccountKeyFile: /home/ipelu/Desktop/work/clouds/yandex/auth.json
openUser: ubuntu # cloud-user
cloudID: b1gv4hq5u08rjf91v2an
folderID: b1g66eha3mp8lc8iic45
zone: ru-central1-a
platformID: standard-v1
imageID: fd8vgqmrilk8dchj1ccf # Ubuntu 20.04 LTS
#imageID: fd8kg2vksu2r8tq4fr08 # CentOS 8
flavor:
  cores: 8 # https://console.cloud.yandex.com/cloud?section=quotas
  memory: 32 # https://console.cloud.yandex.com/cloud?section=quotas
storageCapacity: 100 # https://console.cloud.yandex.com/cloud?section=quotas
