providerName: yandex
pathToKey: /home/ipelu/.ssh/id_rsa
pathToPubKey: /home/ipelu/.ssh/id_rsa.pub
serviceAccountKeyFile: /home/ipelu/Desktop/work/clouds/yandex/auth_ipeluaga.json # /data/career/cern/clouds/yandex/auth.json
openUser: cloud-user # ubuntu
cloudID: b1gv4hq5u08rjf91v2an
folderID: b1gh16rcufgc7l1it508 # b1g66eha3mp8lc8iic45
zone: ru-central1-a
platformID: standard-v1
imageID: fd8kg2vksu2r8tq4fr08 # CentOS 8
#imageID: fd8vgqmrilk8dchj1ccf # Ubuntu 20.04 LTS
#imageID: fd8hguc7o9hhr5bcvhql # Ubuntu 20.04 LTS GPU
flavor:
  cores: 4
  memory: 16
storageCapacity: 60
